### ISSUE TITLE
reportcard.py what if it misses an APPROACHING bus?

### ISSUE THREAD

**Issue by anthonymobile** [code4jc/buswatcher#2]
is 1/minute frequently enough to grab?

**Comment by reyale** [comment]
I don't think we can know this until we start looking at the data itself.  It'll also depend on if we consider a variance of 1 min to be statistically significant or not.  We could look at a 1 min as a percentage of supposed trip length as a distribution to get a feel if this is significant.

**Comment by anthonymobile** [comment]
after a while this doesnt appear to be an issue. bigger issue is buses appearing at a stop as APPROACHING, then dissappearing for a few minutes and reappearing. have to look at the route geometry, but it seems to happen when the stops are really close and / or a lot of tight turns.
